FROM f5devcentral/f5-api-services-gateway:1.0.3

RUN mkdir -p /root/lx/route53-to-bigip/nodejs/
COPY nodejs /root/lx/route53-to-bigip/nodejs/
RUN npm install --prefix /root/lx/route53-to-bigip/nodejs/
